[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Saudi ANPR - License Plate Detector"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "opencv-python-headless",
    "numpy",
    "onnxruntime",
]
